### ISSUE TITLE
Great open source for applying funding on NLnet

### ISSUE THREAD

**Issue by RED29** [meshtastic/Meshtastic-esp32#24]
I see a great potential that this project focused on open source communication can successfully apply for funding (https://nlnet.nl/foundation/can_do.html). Look also on the themes https://nlnet.nl/themes/ and the project NLnet is supporting; https://nlnet.nl/project/current.html

**Comment by geeksville** [comment]
Interesting!  I just took your advice and applied!

**Comment by RED29** [comment]
If succeed funding send me an unit to play with :-)
