### ISSUE TITLE
Missing library dependency TinyGPS+

### ISSUE THREAD

**Issue by spattinson** [meshtastic/Meshtastic-esp32#28]
V 0.1.6

I added:
```
  https://github.com/mikalhart/TinyGPSPlus.git
```
Line 70 platformio.ini
Now seeing location in debug monitor!

**Comment by geeksville** [comment]
hmm strange.  I though I removed all references that needed tinygps,
because I switched to a different library.  I must have missed one, I'll
investigate soon.

**Comment by geeksville** [comment]
oops - my bad - @girtsf just fixed the root cause: https://github.com/meshtastic/Meshtastic-esp32/pull/30
