### ISSUE TITLE
Oled is upside down

### ISSUE THREAD

**Issue by claesg** [meshtastic/Meshtastic-esp32#50]
Flashed one of my T-Beam's with 0.1.8
The screen is upside down compared to the other T-Beam which is running 0.1.7
![IMG_20200319_193141](https://user-images.githubusercontent.com/13845590/77102368-00e5ac80-6a19-11ea-8d94-abaeedcae679.jpg)
The right one in the picture is running 0.1.8
The T-Beam is a V1.0.

**Comment by girtsf** [comment]
@geeksville - on the T-BEAM that I have, the new orientation looks better (due to the two-color display). But perhaps for majority of people the old orientation makes more sense? Should we revert to the old behavior and have an opt-in define to flip it?

**Comment by geeksville** [comment]
In fact the one you have girts was a test device I built up - all of the
standard tbeams are monocolor.  So probably just good to turn that ifdef
off for everybody.  The next time I see you we can swap tbeams and I'll
take that screen off and put on the standard one.

(Sent from a phone - please ignore typos)
