### ISSUE TITLE
Bluetooth Won't Pair

### ISSUE THREAD

**Issue by lburrowes** [meshtastic/Meshtastic-esp32#52]
I tried .7 and .8 alpha release and the TTGO V1 will not pair with the phone or tablets.  Shows the pin code on he screen.

**Comment by girtsf** [comment]
I can reproduce with the T-BEAM v1.0. This is what I see in the debug log:

```
Turning on screen
showing bluetooth screen
onAuthenticationComplete -> fail 81
showing standard frames
```

I'll poke at it and see if I can figure out what that means.

**Comment by lburrowes** [comment]
Other bluetooth based code I have loaded on the board works fine.  Only meshtastic has an issue with pairing...
