### ISSUE TITLE
"make bootloader-flash" required for boards with old bootloaders

### ISSUE THREAD

**Issue by Deadolus** [meshtastic/Meshtastic-esp32#54]
I have bought a Heltec Lora in November 2017 and just had it laying around, 
never done anything with it. 
After discovering Meshtastic I decided to give it a try, but apparently my bootloader was too old: 
my display never went lit up or displayed the meshtastic logo. 
After a bit of debugging I executed 
`make bootloader-flash`
from another, recent esp project. 
After this flashed the bootloader, I flashed the Heltec bin again, and now the device is working. 
Just a heads up, that you might want to add this to the troubleshooting section.

**Comment by geeksville** [comment]
Thanks!  I totally agree.  Merging with #27
