### ISSUE TITLE
boot message reports: Meshtastic swver=0.0.0, hwver=1.0 - US

### ISSUE THREAD

**Issue by spattinson** [meshtastic/Meshtastic-esp32#92]
Even if you are set to EU433, I think this is legacy from the old method of selecting hardware and band in configuration.h
It may be a good idea to display which band and hardware is selected in boot messages and on the screen in case someone flashed the wrong firmware. All the sx1276/7/8/9 are advertised to operate over a wide frequency range, I assume that they may operate suboptimally outside of the intended frequency, though its not clear from what I seen scanning semtech datasheet.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ttgo-t-beam-gps/98/15

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ttgo-t-beam-gps/98/23
